### ISSUE TITLE
Mozilla Animation Issue

### ISSUE THREAD

**Issue by mravinash** [millerbennett/jquery-bootstrap-dropdown-on-hover#1]
Hi, 
Awesome plugin there i am facing issues with mozilla the animation appears just once and next time i hover on the item its gone. Its working awesomely on Chrome.

**Comment by millerbennett** [comment]
Ok, I will take a look.

**Comment by mravinash** [comment]
Thanks :+1:

**Comment by millerbennett** [comment]
What version of firefox?

**Comment by mravinash** [comment]
Its 38.0.1

**Comment by millerbennett** [comment]
I've pushed a fix for this issue. In order to fix it, I needed to isolate the animation attached to the menu. To see the fix, please specify the animation in a `data-animation` attribute.

``` html
<ul class="dropdown-menu animated" data-animation="flipInX">
    <li><a href="#">First</a></li>
    <li><a href="#">Second</a></li>
    <li><a href="#">Third</a></li>
</ul>
```

Let me know if that fixes the issue you are seeing.

**Comment by avinashksmeindia** [comment]
Thanks working fine now :)
